spring.application.name=Studexa

spring.datasource.url=jdbc:postgresql://localhost:5432/Studexa
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

aws.accesskey = ${AWS_ACCESS_KEY}
aws.secretkey = ${AWS_SECRET_KEY}
aws.region = ap-south-1
aws.s3.bucket = studexa-bucket

spring.graphql.schema.introspection.enabled=true